pub const API_ADDRESS: &str = "API_ADDRESS";
pub const API_PORT: &str = "API_PORT";
pub const API_AUTHORIZATION_SECRET: &str = "API_AUTHORIZATION_SECRET";

pub const POSTGRES_HOST: &str = "POSTGRES_HOST";
pub const POSTGRES_PORT: &str = "POSTGRES_PORT";
pub const POSTGRES_USER: &str = "POSTGRES_USER";
pub const POSTGRES_PASSWORD: &str = "POSTGRES_PASSWORD";
pub const POSTGRES_DATABASE: &str = "POSTGRES_DATABASE";
