#!/usr/bin/env bash

export TOOLCHAIN=nightly-2022-07-11
export CARGO_ARGS=(
  --workspace
  --bins
  --examples
  --tests
  --benches
  --all-targets
  --all-features
)
export UNIT_TEST_ARGS=(
  --workspace
)
